// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day1SignalIR.Models;

[Table("Table_1")]
public partial class Table_1
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    public int? Age { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Address { get; set; }
}
